language: ruby

rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1
  - ruby-head
  - jruby-19mode
  - jruby-head
  - rbx-2

matrix:
  allow_failures:
    - rvm: rbx-2
    - rvm: jruby-head
    - rvm: ruby-head

# script: bundle exec rspec spec
env:
  global:
    - JAVA_OPTS="-server -Djruby.cext.enabled=false -Djruby.compile.invokedynamic=false"

notifications:
  irc: "irc.freenode.net#rubber"
