language: ruby
sudo: false
cache: bundler

rvm:
  - 2.0.0
  - 2.1
  - 2.2
  - 2.3
  - ruby-head
  - jruby-head
  - rbx-3

matrix:
  allow_failures:
    - rvm: rbx-3
    - rvm: ruby-head

before_install:
  - gem install bundler

# script: bundle exec rspec spec
env:
  global:
    - JAVA_OPTS="-server -Djruby.cext.enabled=false -Djruby.compile.invokedynamic=false"

notifications:
  irc: "irc.freenode.net#rubber"
