graylog_version: "2.2.3-1"
graylog_prefix: "/usr/local"
graylog_dir: "#{graylog_prefix}/graylog2-server-#{graylog_version}"
graylog_pid_file: "/var/run/graylog-server.pid"
graylog_server_port: 12201
graylog_syslog_port: 12514

graylog_web_port: 9000
graylog_web_username: admin
graylog_web_password: admin1

graylog_mongo_database: graylog2
graylog_elasticsearch_index: "graylog2_#{Rubber.env}"

web_tools_proxies:
  graylog:
    role: graylog_web
    port: "#{graylog_web_port}"
    path: /

role_dependencies:
  graylog: [graylog_mongodb, graylog_elasticsearch]
  graylog_server: [graylog]
  graylog_web: [graylog]
  graylog_mongodb: [mongodb]
  graylog_elasticsearch: [elasticsearch]

roles:
  graylog:
    packages: [[graylog-server, "#{graylog_version}"]]
    os_packages:
      '14.04': [openjdk-7-jdk]
      '16.04': [openjdk-8-jdk]

security_groups:
  graylog_web:
    description: "To open up graylog"
    rules:
      - protocol: tcp
        from_port: "#{graylog_web_port}"
        to_port: "#{graylog_web_port}"
        source_ips: [0.0.0.0/0]
